apiVersion: v1
kind: Service
metadata:
  name: {{ include "chaos-kraken.fullname" . }}
  labels:
{{ include "chaos-kraken.labels" . | indent 4 }}
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
    name: http
  - port: 9090
    protocol: TCP
    targetPort: 9090
    name: metrics
  selector:
    app.kubernetes.io/instance: chaos-kraken
    app.kubernetes.io/name: chaos-kraken
  type: LoadBalancer